# OpenAPI version identifier - required for OpenAPI 3.0 domains
openapi: 3.0.3

#######################
# info section
#######################
info:
  title: AvanChange API
  x-logo:
	url: avanchange.com/uploads/images/logo-api.png
  description: >-
	This page contains the documentation on how to use
	[AvanChange](https://avanchange.com) through API calls.

	> Note: You need to register on the
	[avanchange.com](https://avanchange.com), next go to the **My Account**
	&raquo; **API** section to get your API Key & Secret.

	## Endpoint Names and Response Content-Type

	The Content-Type for `POST` requests can be set to `application/json` to the
	request to get the JSON response. Most API endpoints provide the same
	content as their HTML counterparts. Sending requests with the Accept header
	is necessary.

	## Authentication

	Some endpoints do not require any authentication, pretty much anything else
	will require you to be authenticated. To become authenticated you will need to create an API Key from the admin panel. Once you have your API Key you can pass it in along with your API Secret as
	an HTTP header like this:

	```

	curl -X GET "https://api.avanchange.com/v1/endpoint/" \

	-H "API-Key: b94a80ec048f" \

	-H "API-Secret: Y3oZu4Cz1Mei2DjV"

	```

	and this is how POST requests will look:

	```

	curl -X POST "https://api.avanchange.com/v1/endpoint/" \

	-H "Content-Type: application/json;" \
	
	-H "API-Key: b94a80ec048f" \

	-H "API-Secret: Y3oZu4Cz1Mei2DjV"
	
  version: '1.0'

components:

  #########################
  # Common headers
  # (except request headers - they are defined as parameters)
  #########################
  headers:
	X-RateLimit-Limit:
	  description: Request limit per hour
	  schema:
		type: integer
	  example: 100
	X-RateLimit-Remaining:
	  description: Remaining requests for the hour
	  schema:
		type: integer
	  example: 100


#########################
# Servers
#########################
servers:
  - url: 'https://api.avanchange.com/v1'
  - url: 'https://avanchange.com/api/v1'
  
  
#########################
# Paths
#########################
paths:
  /exchange/get_currencies:
	summary: Exchange
	description: Get all payment methods codes with human friendly names
	get:
	  summary: Currency codes
	  description: Get all available currency codes with human friendly names
	  operationId: '1'
	  responses:
		'200':
		  description: Success
		  content:
			application/json:
			  examples:
				List of codes:
				  value: |-
					{
					  "BTC": "Bitcoin",
					  "ETH": "Ethereum",
					  "XMR": "Monero (XMR)",
					  "TUSD": "TrueUSD (TUSD)",
					  "QWRUB": "Qiwi (RUB)",
					  "others": "...",
					}
	  tags:
		- Exchange
  /exchange/get_rates:
	summary: Exchange
	description: Actions with exchange rates and etc
	get:
	  summary: Rates
	  description: Get all exchange directions rates
	  operationId: '2'
	  responses:
		'200':
		  description: Success
		  content:
			application/json:
			  examples:
				Short example:
				  value: |-
					{
					  "from": "BTC",
					  "from_title": "Bitcoin",
					  "to": "QWRUB",
					  "to_title": "QIWI (RUB)",
					  "rate": "1709159.47",
					  "reserve": "500000",
					  "min": "5000",
					  "max": "45000"
					},
					{
					  "from": "BTC",
					  "from_title": "Bitcoin",
					  "to": "YMRUB",
					  "to_title": "Яндекс Деньги",
					  "rate": "1712010.37",
					  "reserve": "500000",
					  "min": "1000",
					  "max": "45000"
					}
	  tags:
		- Exchange
  /exchange/get_rate/{symbol}:
	summary: Single direction rate
	description: Get rate for selected direction
	get:
	  summary: 'Single Rate'
	  description: Get rate for selected direction
	  operationId: '3'
	  parameters:
		- name: symbol
		  in: path
		  required: true
		  example: BTC-QWRUB
		  description: Exchange direction with currency codes, separated by a dash. <a href="#">List of currencies codes</a>
		  schema:
			type: string
			pattern: ^[A-Z]{3,8}-[A-Z]{3,8}$
			minLength: 7
	  responses:
		'200':
		  description: Success
		  content:
			application/json:
			  examples:
				Short example:
				  value: |-
					{
					  "from": "BTC",
					  "from_title": "Bitcoin",
					  "to": "QWRUB",
					  "to_title": "QIWI (RUB)",
					  "rate": "1709159.47",
					  "reserve": "500000",
					  "min": "5000",
					  "max": "45000"
					}
	  tags:
		- Exchange
